name: Test Quote API

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: "Create env file"

        run: |
          touch .env
          echo MONGODB_URI= ${{ secrets.MONGODB_URI }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} >> .env
          echo HMAC_SECRET_KEY=${{ secrets.HMAC_SECRET_KEY }} >>.env
          cat .env

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
