name: Test Quote API

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: "Create env file"

        run: |
          touch .env
          echo MONGODB_URI= "${{ secrets.MONGODB_URI }}" >> .env
          echo PORT= "${{ secrets.PORT }}" >> .env
          echo TOKEN_SECRET= "${{ secrets.TOKEN_SECRET }}" >> .env
          echo HMAC_SECRET_KEY= "${{ secrets.HMAC_SECRET_KEY }}" >>.env
          cat .env

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test

      - name: Create gh-pages branch and deploy report
        run: |

          # Make sure the reports directory exists (if it doesn't, create it)
          mkdir -p reports

          # Copy the generated index.html to the reports folder
          cp reports/index.html ./index.html

          # Configure Git for GitHub Pages
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Commit and push the HTML report to the main branch
          git add index.html
          git commit -m "Deploy Jest test HTML report to GitHub Pages"
          git push https://x-access-token:${{ secrets.TOKEN }}@github.com/Geeks-Vegeta/QuoteApi.git main

      - name: Clean up
        run: |
          rm -rf reports
